# snakemake --dryrun --printshellcmds --reason --jobs 1 --resources load=100
# snakemake --printshellcmds --reason --jobs "$(($(nproc --all) / 2))" --resources load=100

import os

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Define master rule (forces Snakemake to generate all missing files)
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

DATADIR = "/fs/cbsubscb17/storage/projects/CLIPNET/data/k562/"
# REFDIR = "/local/workdir/James/PauseEvolution/data/human_K562/"
REFDIR = "/fs/cbsubscb17/storage/data/hg38/k562/proseq_dreg_datasets/"
WORKDIR = "/workdir/ayh8/data/k562/"
samples = ["G1", "G5", "G6", "G156"]

output = expand(
    os.path.join(DATADIR, "initiation/k562_initiation_{sample}.bed"),
    sample=samples,
)


rule proseq_all:  # A master rule that ensures all the other rules run
    input:
        output,
    params:
        WORKDIR,
    shell:
        "echo rm -r {params}"


rule unpack_active_transcripts:
    input:
        os.path.join(REFDIR, "denr_transcript_abundance_rpb_1.bed.gz"),
    output:
        os.path.join(WORKDIR, "denr_transcript_abundance_rpb_1.bed"),
    shell:
        "gunzip -c {input} > {output}"


rule unpack_bigwigs:
    input:
        os.path.join(REFDIR, "K562_proseq_{sample}/K562_proseq_{sample}_QC_{strand}.bw"),
    output:
        os.path.join(WORKDIR, "K562_proseq_{sample}_QC_{strand}.bw"),
    shell:
        "rsync {input} {output}"


rule unpack_merged_bigwigs:
    input:
        os.path.join(REFDIR, "K562_proseq_G156_QC_{strand}.bw"),
    output:
        os.path.join(WORKDIR, "K562_proseq_G156_QC_{strand}.bw"),
    shell:
        "rsync {input} {output}"


rule calculate_initiation:
    input:
        pl_bw=os.path.join(WORKDIR, "K562_proseq_{sample}_QC_plus.bw"),
        mn_bw=os.path.join(WORKDIR, "K562_proseq_{sample}_QC_minus.bw"),
        bed=os.path.join(WORKDIR, "denr_transcript_abundance_rpb_1.bed"),
    output:
        os.path.join(DATADIR, "initiation/k562_initiation_{sample}.bed"),
    shell:
        "python ../../data_processing_scripts/pausing_index.py {input} --{output}"


rule calculate_merged_initiation:
    input:
        pl_bw=os.path.join(WORKDIR, "K562_proseq_G156_QC_plus.bw"),
        mn_bw=os.path.join(WORKDIR, "K562_proseq_G156_QC_minus.bw"),
        bed=os.path.join(WORKDIR, "denr_transcript_abundance_rpb_1.bed"),
    output:
        os.path.join(DATADIR, "initiation/k562_initiation_G156.bed"),
    shell:
        "python ../../data_processing_scripts/pausing_index.py {input} {output}"
