import os

# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Define master rule (forces Snakemake to generate all missing files)
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

DATADIR = "/fs/cbsubscb17/storage/projects/CLIPNET/data/k562/"
WORKDIR = "/workdir/ayh8/k562/"
RAWDIR = "/fs/cbsubscb17/storage/data/hg38/k562/groseq_tss/"
fold_assignments = "../../clipnet_data_folds/data_fold_assignments.csv"
FOLDS = 10

output = [
    os.path.join(DATADIR, f"k562_data_folds/k562_sequence_{fold}.npz")
    for fold in range(FOLDS)
]
output_fa = [
    os.path.join(DATADIR, f"k562_data_folds/k562_sequence_{fold}.fna.gz")
    for fold in range(FOLDS)
]


rule sequence_all:  # A master rule that ensures all the other rules run
    input:
        output,
        output_fa,
    params:
        WORKDIR,
    shell:
        "echo rm -r {params}"


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Get DNA sequence of windows
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


rule unpack_windows:
    input:
        os.path.join(DATADIR, "coords/procap_tss_1kb_windows.bed.gz"),
    output:
        os.path.join(WORKDIR, "coords/procap_tss_1kb_windows.bed"),
    shell:
        "gunzip -c {input} > {output}"


# format bed coordinates to seqList format
rule make_seqList:
    input:
        os.path.join(WORKDIR, "coords/procap_tss_1kb_windows.bed"),
    output:
        os.path.join(WORKDIR, "coords/procap_tss_1kb_windows.seqList"),
    shell:
        "bash ../../data_processing_scripts/make_seqList.sh {input} > {output}"


# use seqList to filter 2bit file to fna file.
rule get_window_sequences:
    input:
        twoBit="/fs/cbsubscb17/storage/data/hg38/hg38.2bit",
        seqList=os.path.join(WORKDIR, "coords/procap_tss_1kb_windows.seqList"),
    params:
        os.path.join(WORKDIR, "sequence/k562_sequence.fna"),
    output:
        os.path.join(WORKDIR, "sequence/k562_sequence.fna.gz"),
    shell:
        """
        twoBitToFa {input.twoBit} -seqList={input.seqList} {params}
        bgzip {params}
        """


# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Split sequence files into train, validation and test
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


rule split_sequence:
    input:
        fna=os.path.join(WORKDIR, "sequence/k562_sequence.fna.gz"),
    resources:
        load=1,
    params:
        fold_assignments=fold_assignments,
        fold="{fold}",
    output:
        fna=os.path.join(DATADIR, "k562_data_folds/k562_sequence_{fold}.fna.gz"),
    run:
        from Bio import SeqIO, bgzf
        import gzip
        import pandas as pd

        fold_assignments = pd.read_csv(
            params.fold_assignments, header=0, index_col=None
        )
        chroms = list(
            fold_assignments[fold_assignments["fold"] == int(params.fold)].chrom
        )

        recs = []
        with gzip.open(input.fna, "rt") as f:
            for rec in SeqIO.parse(f, "fasta"):
                chrom = rec.id.split(":")[0].split("_")[-1]
                if chrom in chroms:
                    recs.append(rec)

        with bgzf.BgzfWriter(output.fna, "wb") as out:
            SeqIO.write(recs, out, "fasta")


rule numpify_fasta:
    input:
        fna=os.path.join(DATADIR, "k562_data_folds/k562_sequence_{fold}.fna.gz"),
    output:
        npz=os.path.join(DATADIR, "k562_data_folds/k562_sequence_{fold}.npz"),
    run:
        import numpy as np
        import sys

        sys.path.append("../../clipnet/")
        import utils

        seq_array = utils.get_onehot_fasta_sequences(input.fna, cores=1)
        np.savez_compressed(output.npz, seq_array)
